/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type ActivityActionType C.enum_EDiscordActivityActionType

const (
	ActivityActionTypeJoin     ActivityActionType = C.DiscordActivityActionType_Join
	ActivityActionTypeSpectate                    = C.DiscordActivityActionType_Spectate
)
