/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type ActivityType C.enum_EDiscordActivityType

const (
	ActivityTypePlaying   ActivityType = C.DiscordActivityType_Playing
	ActivityTypeStreaming              = C.DiscordActivityType_Streaming
	ActivityTypeListening              = C.DiscordActivityType_Listening
	ActivityTypeWatching               = C.DiscordActivityType_Watching
)
