/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type ActivityJoinRequestReply C.enum_EDiscordActivityJoinRequestReply

const (
	ActivityJoinRequestReplyNo     ActivityJoinRequestReply = C.DiscordActivityJoinRequestReply_No
	ActivityJoinRequestReplyYes                             = C.DiscordActivityJoinRequestReply_Yes
	ActivityJoinRequestReplyIgnore                          = C.DiscordActivityJoinRequestReply_Ignore
)
