/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

const (
	DiscordVersion                    = C.DISCORD_VERSION
	DiscordApplicationManagerVersion  = C.DISCORD_APPLICATION_MANAGER_VERSION
	DiscordUserManagerVersion         = C.DISCORD_USER_MANAGER_VERSION
	DiscordImageManagerVersion        = C.DISCORD_IMAGE_MANAGER_VERSION
	DiscordActivityManagerVersion     = C.DISCORD_ACTIVITY_MANAGER_VERSION
	DiscordRelationshipManagerVersion = C.DISCORD_RELATIONSHIP_MANAGER_VERSION
	DiscordLobbyManagerVersion        = C.DISCORD_LOBBY_MANAGER_VERSION
	DiscordNetworkManagerVersion      = C.DISCORD_NETWORK_MANAGER_VERSION
	DiscordOverlayManagerVersion      = C.DISCORD_OVERLAY_MANAGER_VERSION
	DiscordStorageManagerVersion      = C.DISCORD_STORAGE_MANAGER_VERSION
	DiscordStoreManagerVersion        = C.DISCORD_STORE_MANAGER_VERSION
	DiscordVoiceManagerVersion        = C.DISCORD_VOICE_MANAGER_VERSION
	DiscordAchievementManagerVersion  = C.DISCORD_ACHIEVEMENT_MANAGER_VERSION
)
