/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type EntitlementType C.enum_EDiscordEntitlementType

const (
	EntitlementTypePurchase            EntitlementType = C.DiscordEntitlementType_Purchase
	EntitlementTypePremiumSubscription                 = C.DiscordEntitlementType_PremiumSubscription
	EntitlementTypeDeveloperGift                       = C.DiscordEntitlementType_DeveloperGift
	EntitlementTypeTestModePurchase                    = C.DiscordEntitlementType_TestModePurchase
	EntitlementTypeFreePurchase                        = C.DiscordEntitlementType_FreePurchase
	EntitlementTypeUserGift                            = C.DiscordEntitlementType_UserGift
	EntitlementTypePremiumPurchase                     = C.DiscordEntitlementType_PremiumPurchase
)
