/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type InputModeType C.enum_EDiscordInputModeType

const (
	InputModeTypeVoiceActivity InputModeType = C.DiscordInputModeType_VoiceActivity
	InputModeTypePushToTalk                  = C.DiscordInputModeType_PushToTalk
)
