/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type LobbySearchDistance C.enum_EDiscordLobbySearchDistance

const (
	LobbySearchDistanceLocal    LobbySearchDistance = C.DiscordLobbySearchDistance_Local
	LobbySearchDistanceDefault                      = C.DiscordLobbySearchDistance_Default
	LobbySearchDistanceExtended                     = C.DiscordLobbySearchDistance_Extended
	LobbySearchDistanceGlobal                       = C.DiscordLobbySearchDistance_Global
)
