/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type LobbySearchComparison C.enum_EDiscordLobbySearchComparison

const (
	LobbySearchComparisonLessThanOrEqual    LobbySearchComparison = C.DiscordLobbySearchComparison_LessThanOrEqual
	LobbySearchComparisonLessThan                                 = C.DiscordLobbySearchComparison_LessThan
	LobbySearchComparisonEqual                                    = C.DiscordLobbySearchComparison_Equal
	LobbySearchComparisonGreaterThan                              = C.DiscordLobbySearchComparison_GreaterThan
	LobbySearchComparisonGreaterThanOrEqual                       = C.DiscordLobbySearchComparison_GreaterThanOrEqual
	LobbySearchComparisonNotEqual                                 = C.DiscordLobbySearchComparison_NotEqual
)
