/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type LobbyType C.enum_EDiscordLobbyType

const (
	LobbyTypePrivate LobbyType = C.DiscordLobbyType_Private
	LobbyTypePublic            = C.DiscordLobbyType_Public
)
