/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type LogLevel C.enum_EDiscordLogLevel

const (
	LogLevelError LogLevel = C.DiscordLogLevel_Error
	LogLevelWarn           = C.DiscordLogLevel_Warn
	LogLevelInfo           = C.DiscordLogLevel_Info
	LogLevelDebug          = C.DiscordLogLevel_Debug
)
