/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type PremiumType C.enum_EDiscordPremiumType

const (
	PremiumTypeNone  PremiumType = C.DiscordPremiumType_None
	PremiumTypeTier1             = C.DiscordPremiumType_Tier1
	PremiumTypeTier2             = C.DiscordPremiumType_Tier2
)
