/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type RelationshipType C.enum_EDiscordRelationshipType

const (
	RelationshipTypeNone            RelationshipType = C.DiscordRelationshipType_None
	RelationshipTypeFriend                           = C.DiscordRelationshipType_Friend
	RelationshipTypeBlocked                          = C.DiscordRelationshipType_Blocked
	RelationshipTypePendingIncoming                  = C.DiscordRelationshipType_PendingIncoming
	RelationshipTypePendingOutgoing                  = C.DiscordRelationshipType_PendingOutgoing
	RelationshipTypeImplicit                         = C.DiscordRelationshipType_Implicit
)
