/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type Status C.enum_EDiscordStatus

const (
	StatusOffline      Status = C.DiscordStatus_Offline
	StatusOnline              = C.DiscordStatus_Online
	StatusIdle                = C.DiscordStatus_Idle
	StatusDoNotDisturb        = C.DiscordStatus_DoNotDisturb
)
