/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type (
	ClientId         C.DiscordClientId
	Version          C.DiscordVersion
	Snowflake        C.DiscordSnowflake
	Timestamp        C.DiscordTimestamp
	UserId           C.DiscordUserId
	Locale           C.DiscordLocale
	Branch           C.DiscordBranch
	LobbyId          C.DiscordLobbyId
	LobbySecret      C.DiscordLobbySecret
	MetadataKey      C.DiscordMetadataKey
	MetadataValue    C.DiscordMetadataValue
	NetworkPeerId    C.DiscordNetworkPeerId
	NetworkChannelId C.DiscordNetworkChannelId
	Path             C.DiscordPath
	DateTime         C.DiscordDateTime
)
