/*generated by internal*/
package dgsdk

/*
#include "src/c/discord_game_sdk.h"
*/
import "C"

type UserFlag C.enum_EDiscordUserFlag

const (
	UserFlagPartner         UserFlag = C.DiscordUserFlag_Partner
	UserFlagHypeSquadEvents          = C.DiscordUserFlag_HypeSquadEvents
	UserFlagHypeSquadHouse1          = C.DiscordUserFlag_HypeSquadHouse1
	UserFlagHypeSquadHouse2          = C.DiscordUserFlag_HypeSquadHouse2
	UserFlagHypeSquadHouse3          = C.DiscordUserFlag_HypeSquadHouse3
)
