package internal

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path"
	"path/filepath"
)

const HeaderPath = "src/c/discord_game_sdk.h"

var HeaderPathNative = filepath.Join(path.Split(HeaderPath))

func HeaderBytes() []byte {
	f, err := os.Open(HeaderPathNative)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	bytes, err := ioutil.ReadAll(f)
	f.Close()
	if err != nil {
		panic(err)
	}

	return bytes
}

func HeaderString() string {
	return string(HeaderBytes())
}

func GoHeader(w io.Writer) {
	_, err := fmt.Fprintf(w, "/*generated by internal*/\npackage dgsdk\n\n/*\n#include \"%s\"\n*/\nimport \"C\"\n\n", HeaderPath)
	if err != nil {
		panic(err)
	}
}
